# Generated by Django 3.2 on 2021-05-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210517_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='default_first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='default_last_name',
        ),
    ]
