# Generated by Django 3.2 on 2021-05-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210517_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='default_first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='default_last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
