# Generated by Django 3.2 on 2021-05-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210517_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='default_first_name',
            new_name='default_full_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='default_last_name',
        ),
    ]
