# Generated by Django 3.2 on 2021-05-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_auto_20210517_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('height', models.DecimalField(decimal_places=0, max_digits=6)),
                ('width', models.DecimalField(decimal_places=0, max_digits=6)),
                ('size', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=13)),
                ('price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=13)),
                ('provide_source_files', models.BooleanField(default=False)),
                ('source_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_processed', models.BooleanField(default=False)),
                ('testimonial', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design_requests.category')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.client')),
            ],
        ),
    ]
