# Generated by Django 3.2 on 2021-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_requests', '0002_remove_designrequest_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='order_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='testimonial',
            field=models.TextField(blank=True, default=False, null=True),
        ),
    ]
