# Generated by Django 3.2 on 2021-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_requests', '0003_auto_20210524_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='order_number',
            field=models.CharField(max_length=32),
        ),
    ]
