# Generated by Django 3.2 on 2021-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=6, null=True),
        ),
    ]
