# Generated by Django 3.2 on 2021-05-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210513_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
