# Generated by Django 3.2 on 2021-05-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='testimonial',
            field=models.TextField(default=False),
        ),
    ]
