# Generated by Django 3.2 on 2021-05-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_requests', '0001_initial'),
        ('orders', '0013_remove_order_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processed_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='provide_source_files',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='source_img',
        ),
        migrations.RemoveField(
            model_name='order',
            name='testimonial',
        ),
        migrations.RemoveField(
            model_name='order',
            name='width',
        ),
        migrations.AddField(
            model_name='order',
            name='design_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_request', to='design_requests.designrequest'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
