# Generated by Django 3.2 on 2021-05-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_requests', '0001_initial'),
        ('orders', '0014_auto_20210519_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design_request',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_request', to='design_requests.designrequest'),
        ),
    ]
