# Generated by Django 3.2 on 2021-05-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_stripe_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
