# Generated by Django 3.2 on 2021-05-12 09:41

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('height', models.DecimalField(decimal_places=0, max_digits=6)),
                ('width', models.DecimalField(decimal_places=0, max_digits=6)),
                ('size', models.DecimalField(decimal_places=0, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('provide_source_files', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('upload', models.FileField(null=True, upload_to=products.models.design_request_directory_path)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
